name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  claude-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v2
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Additional configuration can be added here
          # project_root: "."
          # exclude_patterns: "*.log,node_modules/"
