name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Claude Code Action
        uses: anthropic/claude-code-action@v2
        with:
          api_key: ${{ secrets.CLAUDE_API_KEY }}
          # Additional configuration can be added here
          # project_root: "."
          # exclude_patterns: "*.log,node_modules/"